DROP TABLE IF EXISTS proj_assignments;
DROP TABLE IF EXISTS thaw_dates;
DROP TABLE IF EXISTS sample_uses;
DROP TABLE IF EXISTS samples;
DROP TABLE IF EXISTS boxes;
DROP TABLE IF EXISTS projects;
DROP TABLE IF EXISTS users;
DROP TABLE IF EXISTS freezers;